# Setup

```{r}
library(dplyr)
library(tidyr)
library(lubridate)
library(readr)
library(stringr)
library(qualtRics)
library(zoo)
```

```{r}
ema <- read_survey("data/regret_ema.csv")
intake <- read_survey("data/regret_ema_intake.csv")
```

# Processing

## EMA

```{r}
df_ema <- ema %>%
  #filter(str_detect(RecordedDate, "^\\d{4}-\\d{2}-\\d{2}")) %>%  # eliminate junk rows.. lmk if you want me to move away from regex
  mutate(RecordedDate = ymd_hms(RecordedDate)) %>%
  arrange(PID, RecordedDate) %>%
  group_by(PID) %>%
  mutate(PING_NUM = row_number()) %>%
  ungroup() %>%
  select(-c(StartDate:UserLanguage)) %>%
    relocate(PID, DAY_NUM, SURVEY_TYPE, DECISION, DECISION_TO_SHOW, NEXT_SURVEY) %>%
    filter(PID != "000000")
```

## Intake

```{r}
df_intake <- intake %>%
  group_by(PID) %>%
  arrange(desc(rowSums(!is.na(.)))) %>%
  slice(1) %>%
  ungroup() %>%
  select(-c(EndDate:UserLanguage)) %>%
   relocate(PID) %>%
    filter(PID != "000000")
```

## Merging EMA and intake + cleaning 

```{r}
df_ema_intake <- df_ema %>%
  # cleaning up and merging "resolved" from the first regret reports and followup reports
    mutate(resolved_fu = as.numeric(`resolved...59`),
           resolved_gen = as.numeric(`resolved...34`)) %>%
    mutate(resolved = coalesce(resolved_fu, resolved_gen)) %>%
    select(-c(`resolved...59`, `resolved...34`, resolved_gen, resolved_fu)) %>%
  # survey type "first" for first-ever survey of the EMA
  mutate(SURVEY_TYPE = ifelse(is.na(SURVEY_TYPE), "first", SURVEY_TYPE)) %>%
  left_join(df_intake, by = "PID") %>%
  arrange(PID, PING_NUM) %>%
  group_by(PID) %>%
  # identifying where regret events start and end
  mutate(
    regret_START = ifelse(regret_yn == 2, 1, NA),
    regret_END = ifelse(
      (regret_yn == 2 & resolved == 1 ) |
      (SURVEY_TYPE == "followup" & lead(SURVEY_TYPE) == "general"),
      1, NA
    )) |>
  # counting up number of regret starts per participant (ie number of regret events)
    mutate(regret_count = sum(regret_START == 1, na.rm = TRUE)
  ) |>
  # making start and end markers + STARTEND for when it starts and resolved in the same ping
  mutate(regret_status = case_when(
    regret_START == 1 & is.na(regret_END) ~ "START",
    regret_END == 1 & is.na(regret_START) ~ "END",
    regret_START == 1 & regret_END == 1 ~ "STARTEND",
  )) |>
  # creating a variable that's 1 when a regret is active and 0 when it's not
  mutate(regret_marker = case_when(
    regret_status == "START"     ~ 1,
    regret_status == "STARTEND" ~ 2,
    regret_status == "END"       ~ -1,
    TRUE                         ~ 0
  )) %>%
  mutate(
    regret_active = {
      flag <- 0
      state <- integer(n())
      for (i in seq_along(regret_marker)) {
        if (regret_marker[i] == 1) {
          flag <- 1
          state[i] <- 1
        } else if (regret_marker[i] == 2) {
          state[i] <- 1
        } else if (regret_marker[i] == -1) {
          state[i] <- flag
          flag <- 0
        } else {
          state[i] <- flag
        }
      }
      state
    }
  ) |> 
  select(-regret_marker) |>
  # assigning IDs to regret events within participant
  mutate(
    regret_event_start = case_when(
      regret_status %in% c("START", "STARTEND") ~ 1,
      lag(regret_status) == "END" & regret_status %in% c("START", "STARTEND") ~ 1,
      is.na(lag(regret_active)) & regret_active == 1 ~ 1,
      TRUE ~ 0
    ),
    regret_id = if_else(regret_active == 1, cumsum(regret_event_start), NA_integer_)
  ) |>
  ungroup() |>
  # tallying up ping_num within a regret event
  group_by(PID, regret_id) |>
  mutate(followup_id = ifelse(!is.na(regret_id), row_number(), NA)) |>
  ungroup() |>
  select(-c(regret_START, regret_END, regret_status, regret_active, regret_event_start)) |>
  # combining identical variables from general and followup type surveys
  mutate(regret_intensity = coalesce(`regret_intensity_1...20`, `regret_intensity_1...45`),
         er_reapp = coalesce(`regret_regulation_1...21`, `regret_regulation_1...46`),
         er_pleasure = coalesce(`regret_regulation_2...22`, `regret_regulation_2...47`),
         er_distract = coalesce(`regret_regulation_3...23`, `regret_regulation_3...48`),
         er_sitmod = coalesce(`regret_regulation_4...24`, `regret_regulation_4...49`),
         er_socsupp = coalesce(`regret_regulation_5...25`, `regret_regulation_5...50`),
         er_accept = coalesce(`regret_regulation_6...26`, `regret_regulation_6...51`),
         er_otherreg = coalesce(`regret_regulation_7...27`, `regret_regulation_7...52`),
         er_otherreg_text = coalesce(`regret_regulation_7_TEXT...28`, `regret_regulation_7_TEXT...53`),
         rumination = coalesce(`rumination...29`, `rumination...54`),
         reverse_undo = coalesce(`reverse_1...30`, `reverse_1...55`),
         reverse_makeup = coalesce(`reverse_2...31`, `reverse_2...56`),
         reverse_plan = coalesce(`reverse_3...32`, `reverse_3...57`),
         reverse_amends = coalesce(`reverse_4...33`, `reverse_4...58`)) |>
  # removing the original variables that were combined
  select(-c(`regret_intensity_1...20`, `regret_intensity_1...45`, 
            `regret_regulation_1...21`, `regret_regulation_1...46`, 
            `regret_regulation_2...22`, `regret_regulation_2...47`, 
            `regret_regulation_3...23`, `regret_regulation_3...48`, 
            `regret_regulation_4...24`, `regret_regulation_4...49`, 
            `regret_regulation_5...25`, `regret_regulation_5...50`, 
            `regret_regulation_6...26`, `regret_regulation_6...51`, 
            `regret_regulation_7...27`, `regret_regulation_7...52`,
            `regret_regulation_7_TEXT...28`, `regret_regulation_7_TEXT...53`,
            `rumination...29`, `rumination...54`,
            `reverse_1...30`, `reverse_1...55`,
            `reverse_2...31`, `reverse_2...56`,
            `reverse_3...32`, `reverse_3...57`,
            `reverse_4...33`, `reverse_4...58`)) |>
  # combining rumination from mood and regret surveys since the question is the same
  mutate(rumination = coalesce(rumination, rumination_nr)) |>
  select(-rumination_nr) |>
  # renaming emotion variables 
  rename(joy = emotions_1,
         pride = emotions_2,
         anxiety = emotions_3,
         anger = emotions_4,
         sadness = emotions_5,
         contentment = emotions_6,
         regret = emotions_7,
         disappointment = emotions_8) |>
  # removing consent variables
  select(-c(welcome, reap_downloaded))
  
readr::write_csv(df_ema_intake, "processed_merged.csv")
```

# For participant crediting

```{r}
df_ema_intake |>
  mutate(Date = ymd_hms(StartDate)) |>
  filter(Date <= "2025-5-24") |>
  group_by(PID) |>
  summarise(num_pings = n()) |>
  arrange(PID)
  
```

# Session info

```{r}
sessionInfo() %>%
  capture.output(file = "processing_session_info.txt")

```
