---
title: "analyses"
author: "Kate Petrova"
date: "2025-06-02"
output: html_document
---

# Setup

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(include = TRUE)

if(!suppressWarnings(require(pacman))){install.packages("pacman");library("pacman")}
p_load(tidyverse, tidyr, dplyr, ggplot2, readxl, lme4, stats, effectsize, sjPlot, readr, GLMMadaptive, ggpubr, patchwork, lubridate, qualtRics, purrr, httr, jsonlite, DescTools, ggthemr, ggthemes, bbplot, brms, ggdist, showtext, scales)
```

```{r}
data <- read_csv("../data/processed_merged.csv")
```

```{r}
# aesthetics
ggthemr(palette = "grape", type = "outer", line_weight = 0.5, text_size = 16, spacing = 2, layout = "clear")

swatch()

showtext_auto()
showtext_opts(nseg = 5)
```

# Exploratory analyses

## Regret frequency, duration

```{r}
data |>
  mutate(isregret = ifelse(!is.na(regret_id), 1, 0)) |>
  ggplot(aes(x = isregret)) +
  geom_bar() +
  labs(x = "Regret reported?", y = "Count") +
  scale_x_continuous(breaks = c(0, 1), labels = c("No", "Yes")) 
  
```

```{r}
data |>
  select(PID, regret_count) |>
  distinct() |>
  ggplot(aes(x = regret_count)) +
  geom_histogram(binwidth = 1) +
  labs(x = "Number of regrets reported", y = "Count") +
  # add mean line
  geom_vline(aes(xintercept = median(regret_count, na.rm = TRUE)), color = "black", linetype = "dashed") 

data |>
  select(PID, regret_count) |>
  distinct() |>
  # number of PIDs with regret_coount == 0
  summarise(n = sum(regret_count == 0, na.rm = TRUE)) 
  
```

```{r}
data |>
  select(PID, followup_id) |>
  group_by(PID) |>
  summarize(n_followups = n_distinct(followup_id, na.rm = TRUE)) |>
  ggplot(aes(x = n_followups)) +
  geom_histogram(binwidth = 1) +
  labs(x = "Number of follow-ups", y = "Count") +
  # add mean line
  geom_vline(aes(xintercept = median(n_followups, na.rm = TRUE)), color = "black", linetype = "dashed")

# print range of followup_id
data |>
  select(PID, followup_id) |>
  summarize(min_followup = min(followup_id, na.rm = TRUE), max_followup = max(followup_id, na.rm = TRUE))

```

### Intensity over time

```{r}
data |>
  group_by(PID, regret_id) |>
  mutate(mean_intensity = mean(regret_intensity, na.rm = TRUE)) |>
  mutate(pmc_intensity = regret_intensity - mean_intensity) |>
  ungroup() |>
  group_by(PID, regret_id) |>
  mutate(followup_percent = (followup_id - 1) / (max(followup_id, na.rm = TRUE) - 1)) |>
  ungroup() |>
  select(PID, regret_id, followup_id, pmc_intensity, followup_percent) |>
  ungroup() |>
  ggplot(aes(x = followup_percent, y = pmc_intensity)) +
  geom_point(position = position_jitter(w = 0.025)) +
  geom_smooth(method = "lm") +
  labs(x = "Time from event onset to resolution", y = "Regret intensity") +
  stat_cor(method = "pearson")
```

## Single participant trajectories

```{r}
data |>
  filter(regret_count > 0) |>
  filter(PID == 112204) |> # selecting a single PID to look at in more depth
  ggplot(aes(x = followup_id, y = regret_intensity, group = regret_id, color = factor(regret_id), fill = factor(regret_id))) +
  geom_line() +
  geom_point() +
  labs(x = "Follow-up ID", y = "Regret intensity") +
  facet_wrap(~PID, scales = "free")
```

```{r}
# function to plot each participant individually
plot_participant_trajectories <- function(data, pid) {
  p <- data %>%
    filter(PID == pid, regret_count > 0) %>%
    ggplot(aes(x = followup_id, y = regret_intensity, group = regret_id, color = factor(regret_id))) +
    stat_smooth(method = "lm", se = FALSE, span = 0.1) +
    geom_point() +
    ylim(0, 100) +
    scale_color_brewer(palette = "Set3") +
    scale_x_continuous(breaks = seq(1, 26, by = 5), limits = c(1, 26)) +
    labs(title = paste("PID", pid), x = "Follow-up ID", y = "Regret intensity") +
    theme(legend.position = "none")
  return(p)
}

# plot 
p_list <- lapply(unique(data$PID), function(pid) plot_participant_trajectories(data, pid))

# save plots as pdfs, 6 per page
pdf("../figures/participant_trajectories.pdf", width = 11, height = 8.5)
for (i in seq(1, length(p_list), by = 6)) {
  gridExtra::grid.arrange(grobs = p_list[i:min(i+5, length(p_list))], ncol = 2)
}
```

## Strategies

```{r}
data |>
  select(-(er_otherreg_text)) |>
  pivot_longer(cols = starts_with("er_"), names_to = "strategy", values_to = "value") |>
  filter(!is.na(regret_id)) |>
  filter(value == 1) |>
  mutate(strategy = case_when(
  strategy == "er_accept" ~ "acceptance",
  strategy == "er_distract" ~ "distraction",
  strategy == "er_otherreg" ~ "other",
  strategy == "er_pleasure" ~ "pleasure-seeking",
  strategy == "er_reapp" ~ "reappraisal",
  strategy == "er_sitmod" ~ "situation-modification",
  strategy == "er_socsupp" ~ "social support"
)) |>
  ggplot(aes(x = strategy, fill = strategy)) +
  geom_bar(position = "dodge") +
  labs(x = "Strategy", y = "Count (N = 1,517 pings)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme(legend.position = "none") +
  coord_flip()
  
```

```{r}
data |>
  ggplot(aes(x = regret_intensity, y = reverse_plan)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_cor(method = "pearson")
```

## Rumination

```{r}
data |>
  filter(!is.na(regret_id)) |>
  ggplot(aes(regret_intensity, rumination)) +
  geom_point(position = position_jitter(h = 0.2)) +
  #geom_smooth(method = "lm") +
  labs(x = "Regret intensity", y = "Rumination") +
  # y axis labels 1 = "haven't thought about it at all", 2 = "thought about it a little", 3 = "thought about it a lot", 4 = "couldn't stop thinking about it"\
  scale_y_continuous(breaks = 1:4, labels = c("Haven't thought about it at all", "Thought about it a little", "Thought about it a lot", "Couldn't stop thinking about it")) +
  stat_cor(method = "pearson") 
  
```
## Mood

```{r}
data |>
  # histogram of emotions
  pivot_longer(cols = c(joy:disappointment), names_to = "emotion", values_to = "value") |>
  # plot mean value by emotion
  ggplot(aes(x = emotion, y = value, color = emotion, fill = emotion)) +
  stat_summary(
    fun.data = mean_cl_boot, conf.int = .95, B = 5000,
    geom = "pointrange", linewidth = 1, size = 1,
    shape = 21 
  ) +
  labs(x = "Emotion", y = "Mean value (95% CI)") +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) 
  
  
```

# Suze archive

```{r}
df <- data %>%
  group_by(PID) %>%
  mutate(regret_intensity_pc = as.numeric(scale(regret_intensity, scale = FALSE))) %>%
  ungroup() # person-centering (?)

model_undo <- lmer(reverse_undo ~ regret_intensity_pc + (1 | PID), data = df) #failed to converge as (1 + [predictor] | PID)
tab_model(model_undo)
plot_model(model_undo)

model_makeup <- lmer(reverse_makeup ~ regret_intensity_pc + (1 | PID), data = df)
tab_model(model_makeup)
plot_model(model_makeup)

model_plan <- lmer(reverse_plan ~ regret_intensity_pc + (1 | PID), data = df)
tab_model(model_plan)
plot_model(model_plan)

model_amends <- lmer(reverse_amends ~ regret_intensity_pc + (1 | PID), data = df)
tab_model(model_amends)
plot_model(model_amends)

lm.beta.lmer <- function(mod) {
   b <- fixef(mod)[-1]
   sd.x <- apply(getME(mod,"X")[,-1],2,sd)
   sd.y <- sd(getME(mod,"y"))
   b*sd.x/sd.y
}      #is this model assuming we have at least one predictor?

lm.beta.lmer(model_undo)
lm.beta.lmer(model_makeup)
lm.beta.lmer(model_plan)
lm.beta.lmer(model_amends)
```

## 6 models for ER strategies - Suze
```{r}
model_pleasure  <- lmer(er_pleasure  ~ regret_intensity_pc + (1 + regret_intensity_pc | PID), data = df) # not failing to converge
tab_model(model_pleasure)
lm.beta.lmer(model_pleasure) #sd = 0 ?
model_pleasure_ri <- lmer(er_pleasure ~ regret_intensity_pc + (1 | PID), data = df) # not failing to converge # random intercepts only
tab_model(model_pleasure_ri)

model_distract <- lmer(er_distract ~ regret_intensity_pc + (1 + regret_intensity_pc | PID), data = df) 
tab_model(model_distract)
lm.beta.lmer(model_distract) #sd = 0 ?

model_sitmod <- lmer(er_sitmod ~ regret_intensity_pc + (1 | PID), data = df)
tab_model(model_sitmod)
lm.beta.lmer(model_sitmod)

model_socsupp <- lmer(er_socsupp ~ regret_intensity_pc + (1 | PID), data = df)
tab_model(model_socsupp)
lm.beta.lmer(model_socsupp)

model_accept <- lmer(er_accept ~ regret_intensity_pc + (1 | PID), data = df)
tab_model(model_accept)
lm.beta.lmer(model_accept) 

model_otherreg <- lmer(er_otherreg ~ regret_intensity_pc + (1 + regret_intensity_pc | PID), data = df)
tab_model(model_accept)
lm.beta.lmer(model_otherreg)
```

## Lagged strategy/reversal 
```{r}
df_lag <- df %>%
  filter(!is.na(followup_id)) %>%
  group_by(PID, regret_id) %>%
  filter(n() > 1) %>%
  arrange(PID, regret_id, followup_id)
df_lag <- df_lag %>%
  group_by(PID, regret_id) %>%
  mutate(lag_reverse_undo = lag(reverse_undo)) %>%
  ungroup() %>%
  filter(!is.na(lag_reverse_undo), !is.na(regret_intensity)) %>%
  group_by(PID) %>%
  mutate(lag_reverse_undo_pc = as.numeric(scale(lag_reverse_undo, scale = FALSE))) %>%
  ungroup()

model_lag_undo <- lmer(regret_intensity ~ lag_reverse_undo_pc + (1 + lag_reverse_undo_pc | PID), data = df_lag)
tab_model(model_lag_undo)
plot_model(model_lag_undo)
lm.beta.lmer(model_lag_undo)


df_lag <- df %>%
  filter(!is.na(followup_id)) %>%
  group_by(PID, regret_id) %>%
  filter(n() > 1) %>%
  arrange(PID, regret_id, followup_id)
df_lag <- df_lag %>%
  group_by(PID, regret_id) %>%
  mutate(lag_reverse_makeup = lag(reverse_makeup)) %>%
  ungroup() %>%
  filter(!is.na(lag_reverse_makeup), !is.na(regret_intensity)) %>%
  group_by(PID) %>%
  mutate(lag_reverse_makeup_pc = as.numeric(scale(lag_reverse_makeup, scale = FALSE))) %>%
  ungroup()

model_lag_makeup <- lmer(regret_intensity ~ lag_reverse_makeup_pc + (1 | PID), data = df_lag) #gave singular fit
tab_model(model_lag_makeup)
tab_model(model_lag_makeup)
plot_model(model_lag_makeup)
lm.beta.lmer(model_lag_makeup)


df_lag <- df %>%
  filter(!is.na(followup_id)) %>%
  group_by(PID, regret_id) %>%
  filter(n() > 1) %>%
  arrange(PID, regret_id, followup_id)
df_lag <- df_lag %>%
  group_by(PID, regret_id) %>%
  mutate(lag_reverse_plan = lag(reverse_plan)) %>%
  ungroup() %>%
  filter(!is.na(lag_reverse_plan), !is.na(regret_intensity)) %>%
  group_by(PID) %>%
  mutate(lag_reverse_plan_pc = as.numeric(scale(lag_reverse_plan, scale = FALSE))) %>%
  ungroup()

model_lag_plan <- lmer(regret_intensity ~ lag_reverse_plan_pc + (1 | PID), data = df_lag) #failed to converse
tab_model(model_lag_plan)
plot_model(model_lag_plan)
lm.beta.lmer(model_lag_plan)


df_lag <- df %>%
  filter(!is.na(followup_id)) %>%
  group_by(PID, regret_id) %>%
  filter(n() > 1) %>%
  arrange(PID, regret_id, followup_id)
df_lag <- df_lag %>%
  group_by(PID, regret_id) %>%
  mutate(lag_reverse_amends = lag(reverse_amends)) %>%
  ungroup() %>%
  filter(!is.na(lag_reverse_amends), !is.na(regret_intensity)) %>%
  group_by(PID) %>%
  mutate(lag_reverse_amends_pc = as.numeric(scale(lag_reverse_amends, scale = FALSE))) %>%
  ungroup()

model_lag_amends <- lmer(regret_intensity ~ lag_reverse_amends_pc + (1 + lag_reverse_amends_pc | PID), data = df_lag)
tab_model(model_lag_amends)
plot_model(model_lag_amends)
lm.beta.lmer(model_lag_amends)
```

```{r}
model_1 <- lmer(rumination ~ regret_intensity + (1 | PID), data = data)
tab_model(model_1)
plot_model(model_1)
```


```{r}
data |>
  filter(!is.na(regret_id)) |>
  ggplot(aes(x = followup_id, y = rumination)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x = "Follow-up ID", y = "Rumination") +
  stat_cor(method = "pearson")
```

## lagged models with 2 predictors
```{r}
df <- df %>%
  group_by(PID, regret_id) %>%
  mutate(initial_intensity = regret_intensity[followup_id == 1][1]) %>%
  ungroup()

# Undo 
df_lagged <- df %>%
  filter(!is.na(followup_id)) %>%
  group_by(PID, regret_id) %>%
  filter(n() > 1) %>% 
  arrange(PID, regret_id, followup_id) %>%
  mutate(lag_reverse_undo = lag(reverse_undo)) %>%
  ungroup() %>%
  filter(!is.na(lag_reverse_undo), !is.na(regret_intensity)) %>%
  group_by(PID) %>%
  mutate(lag_reverse_undo_pc = as.numeric(scale(lag_reverse_undo, scale = FALSE))) %>%
  ungroup()
model_lag_undo_initial <- lmer(regret_intensity ~ lag_reverse_undo_pc + initial_intensity + (1 | PID), data = df_lagged)
tab_model(model_lag_undo_initial)
plot_model(model_lag_undo_initial)


# Makeup
df_lagged <- df %>%
  filter(!is.na(followup_id)) %>%
  group_by(PID, regret_id) %>%
  filter(n() > 1) %>% 
  arrange(PID, regret_id, followup_id) %>%
  mutate(lag_reverse_makeup = lag(reverse_makeup)) %>%
  ungroup() %>%
  filter(!is.na(lag_reverse_makeup), !is.na(regret_intensity)) %>%
  group_by(PID) %>%
  mutate(lag_reverse_makeup_pc = as.numeric(scale(lag_reverse_makeup, scale = FALSE))) %>%
  ungroup()
model_lag_makeup_initial <- lmer(regret_intensity ~ lag_reverse_makeup_pc + initial_intensity + (1 | PID), data = df_lagged)
tab_model(model_lag_makeup_initial)
plot_model(model_lag_makeup_initial)

# Plan
df_lagged <- df %>%
  filter(!is.na(followup_id)) %>%
  group_by(PID, regret_id) %>%
  filter(n() > 1) %>% 
  arrange(PID, regret_id, followup_id) %>%
  mutate(lag_reverse_plan = lag(reverse_plan)) %>%
  ungroup() %>%
  filter(!is.na(lag_reverse_plan), !is.na(regret_intensity)) %>%
  group_by(PID) %>%
  mutate(lag_reverse_plan_pc = as.numeric(scale(lag_reverse_plan, scale = FALSE))) %>%
  ungroup()
model_lag_plan_initial <- lmer(regret_intensity ~ lag_reverse_plan_pc + initial_intensity + (1 | PID), data = df_lagged)
tab_model(model_lag_plan_initial)
plot_model(model_lag_plan_initial)

# Amends
df_lagged <- df %>%
  filter(!is.na(followup_id)) %>%
  group_by(PID, regret_id) %>%
  filter(n() > 1) %>% 
  arrange(PID, regret_id, followup_id) %>%
  mutate(lag_reverse_amends = lag(reverse_amends)) %>%
  ungroup() %>%
  filter(!is.na(lag_reverse_amends), !is.na(regret_intensity)) %>%
  group_by(PID) %>%
  mutate(lag_reverse_amends_pc = as.numeric(scale(lag_reverse_amends, scale = FALSE))) %>%
  ungroup()
model_lag_amends_initial <- lmer(regret_intensity ~ lag_reverse_amends_pc + initial_intensity + (1 | PID), data = df_lagged)
tab_model(model_lag_amends_initial)
plot_model(model_lag_amends_initial)

# modeling time since the start of the episode within episodes

df <- df_ema_merged %>%
  filter(!is.na(regret_id), !is.na(regret_intensity), !is.na(recorded_date)) %>%
  arrange(PID, regret_id, recorded_date) %>%
  group_by(PID, regret_id) %>%
  mutate(time_since_start_min = as.numeric(difftime(recorded_date, min(recorded_date), units = "mins")),
    time_point = row_number(),
    initial_intensity = first(regret_intensity)
  ) %>%
  ungroup()

df <- df %>%
  group_by(PID) %>%
  mutate(time_point_pc = as.numeric(scale(time_point, scale = FALSE)), time_minutes_pc = as.numeric(scale(time_since_start_min, scale = FALSE)), initial_intensity_pc = as.numeric(scale(initial_intensity, scale = FALSE))
  ) %>%
  ungroup()

# regret_intensity ~ time
model_time <- lmer(regret_intensity ~ time_point_pc + (1 + time_point_pc | PID), data = df)

# regret_intensity ~ time + initial_intensity
model_time_initial <- lmer(regret_intensity ~ time_point_pc + initial_intensity_pc + (1 + time_point_pc | PID), data = df)

```


```{r}
cor(data$regret_intensity, data$rumination, use = "pairwise.complete.obs", method = "pearson")

model1_lm <- lm(rumination ~ regret_intensity, data = data) 
# standardized beta
summary(model1_lm)
lm.beta(model1_lm)
tab_model(model1_lm)

data |>
  mutate(intensity_std = sd(regret_intensity, na.rm = TRUE)) 
```

```{r}
lm.beta.lmer <- function(mod) {
   b <- fixef(mod)[-1]
   sd.x <- apply(getME(mod,"X")[,-1],2,sd)
   sd.y <- sd(getME(mod,"y"))
   b*sd.x/sd.y
}

data |>
  group_by(PID) |>
  mutate(mean_regret_intensity = mean(regret_intensity, na.rm = TRUE)) |>
  ungroup() |>
  mutate(regret_intensity_pmc = regret_intensity - mean_regret_intensity) 
model1 <- lmer(rumination ~ scale(regret_intensity) + (1 | PID), data = data)
tab_model(model1)

ggthemr_reset()
data |>
  ggplot(aes(x = scale(regret_intensity), y = rumination, group = PID)) +
  #geom_point(position = position_jitter(h = 0.2)) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Regret intensity (PMC)", y = "Rumination") +
# remove legends
  theme(legend.position = "none")
```

```{r}
tab_model(lmer(reverse_undo ~ scale(regret_intensity) + (1 + regret_intensity | PID), data = data))
data |>
  ggplot(aes(x = scale(regret_intensity), y = reverse_undo, group = PID)) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Regret intensity", y = "Reverse undo") 
```

```{r}
tab_model(lmer(regret_intensity ~ lag(er_reapp) + (1 | PID), data = data))
data |> 
  ggplot(aes(x = lag(er_reapp), y = regret_intensity)) +
  stat_smooth(method = "lm", se = FALSE, aes(group = PID)) +
  stat_smooth(method = "lm", se = FALSE, color = "black")
```
